name: Deploy-Android-DEV
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test  
      - name: Build on EAS dev
        run: eas build -p android --profile development
      - name:  Publish update 
        run: eas update --auto
